CREATE DATABASE TRELLO;
USE TRELLO;

CREATE TABLE USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
	FULL_NAME VARCHAR(60) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL
);

CREATE TABLE SET_LISTS (
    ID INT PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE LISTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
	LIST_NAME VARCHAR(60) NOT NULL,
	ID_SET_LIST INT,
    FOREIGN KEY (ID_SET_LIST) REFERENCES SET_LISTS(ID)
);

CREATE TABLE BOARD (
    ID INT PRIMARY KEY AUTO_INCREMENT,
	BOARD_NAME VARCHAR(60) NOT NULL,
	ID_SET_LIST INT,
    ID_ISER INT,
    FOREIGN KEY (ID_SET_LIST) REFERENCES SET_LISTS(ID),
	FOREIGN KEY (ID_ISER) REFERENCES USERS(ID)
);

CREATE TABLE CARD (
    ID INT PRIMARY KEY AUTO_INCREMENT,
	ID_BOARD INT,
    ID_LIST INT,
    CARD_NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(150),
    DATE_FINISH_TASK DATETIME,
    FOREIGN KEY (ID_BOARD) REFERENCES BOARD(ID),
	FOREIGN KEY (ID_LIST) REFERENCES LISTS(ID)
);

CREATE TABLE COMMENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    BODY_COMMENT VARCHAR(300) NOT NULL,
    ID_CARD INT,
    FOREIGN KEY (ID_CARD) REFERENCES CARD(ID)
);



